---
- name: Get gitkraken deb file
  get_url:
    url: https://release.gitkraken.com/linux/gitkraken-amd64.deb
    dest: ~/Downloads/gitkraken.deb
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5
  changed_when: false

- name: Install gitkraken
  become: yes
  apt:
    deb: '{{ ansible_env.HOME }}/Downloads/gitkraken.deb'