---
- block:
    - name: Add fish repository
      apt_repository:
        repo: ppa:fish-shell/release-3
        update_cache: yes
      become: yes

    - name: Install "fish"
      become: yes
      apt:
        name: fish
        autoclean: yes
        autoremove: yes

  tags: fish_install

- block:
    - name: Obtain path to fish
      shell: which fish
      register: fish_path
      changed_when: false

    - name: Change default shell to "fish"
      become: yes
      user:
        name: '{{ ansible_user }}'
        shell: '{{ fish_path.stdout }}'
        system: yes

  tags: fish_chsh

- block:
    - name: Create fish config dir
      file:
        path: ~/.config/fish
        state: directory

    - name: Obtain path to fish
      shell: which fish
      register: fish_path
      changed_when: false
      check_mode: no

    - name: Set ansible_shell_executable to fish
      set_fact:
        ansible_shell_executable: '{{ fish_path.stdout }}'
        ansible_shell_type: fish

    - name: Create functions dir
      file:
        path: ~/.config/fish/functions
        state: directory

    - name: Install fisherman
      get_url:
        url: https://git.io/fisher
        dest: ~/.config/fish/functions/fisher.fish
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: Put config files
      file:
        src: '{{ dotfiles_path }}/{{ item.path }}'
        dest: ~/{{ item.path }}
        state: link
        force: yes
      with_items:
        - '{{ fish_config_file }}'
      changed_when: false

    - name: Install fish plugins
      shell: fisher
      changed_when: false

    - name: reflect config.fish
      shell: source ~/.config/fish/config.fish
      changed_when: false

  tags: fish_config