---
- block:
    - name: Install "fish"
      apt:
        name: fish
        autoclean: yes
        autoremove: yes

  tags: fish_install

# TODO 
#- block:
#    - name: Obtain path to fish
#      shell: which fish
#      register: fish_path
#      changed_when: false
#
#    - name: Change default shell to "fish"
#      user:
#        name: '{{ lookup("env", "USER") }}'
#        shell: '{{ fish_path.stdout }}'
#        system: yes
#
#  tags: fish_chsh

- block:
    - name: Create fish config dir
      file:
        path: ~/.config/fish
        state: directory

    - name: Obtain path to fish
      shell: which fish
      register: fish_path
      changed_when: false
      check_mode: no

    - name: Set ansible_shell_executable to fish
      set_fact:
        ansible_shell_executable: '{{ fish_path.stdout }}'
        ansible_shell_type: fish

    - name: Create functions dir
      file:
        path: ~/.config/fish/functions
        state: directory

    - name: Install fisherman
      get_url:
        url: https://git.io/fisher
        dest: ~/.config/fish/functions/fisher.fish
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: Put config files
      file:
        src: '{{ dotfiles_path }}/{{ fish_config_file }}'
        dest: ~/{{ fish_config_file }}
        state: link
        force: yes

    - name: Install fish plugins
      shell: fisher
      changed_when: false

  tags: fish_config