---
- hosts: localhost
  strategy: linear
  roles:
  - name: tools
    tags: tools

  - name: mac
    tags: mac
    when: ansible_os_family == "Darwin"

  - name: dotfiles
    tags: dotfiles

  - name: fish
    tags: fish

  - name: c
    tags: c

  - name: docker
    tags: docker

  - name: font
    tags: font

  - name: go
    tags: go

  - name: kubernetes
    tags: kubernetes

  - name: neovim
    tags: neovim

  - name: tex
    tags: tex

  - name: tmux
    tags: tmux
