---
- block:
    - name: Apt update
      become: yes
      apt:
        update_cache: yes

    - name: Install packages
      become: yes
      apt:
        name: '{{ tex_apt_packages }}'

    - name: Apt clean
      become: yes
      apt:
        autoclean: yes

    - name: Remove unnecessary packages
      become: yes
      apt:
        autoremove: yes

  tags: tex_install
