---
- name: git clone my dotfiles
  git:
    repo: https://github.com/chez-shanpu/dotfiles
    dest: '{{ dotfiles_path }}'
    force: yes

- name: Put ".gitconfig" to home
  file:
    src: '{{ dotfiles_path }}/.gitconfig'
    dest: ~/.gitconfig
    state: link
    force: yes
  changed_when: false


