---
- name: Install chezmoi
  community.general.homebrew:
    name:
    - chezmoi

- name: chezmoi init
  changed_when: false
  shell: chezmoi init https://github.com/chez-shanpu/dotfiles

- name: chezmoi apply
  changed_when: false
  shell: chezmoi apply -v
