---
- hosts: all
  become: yes
  vars:
    github_user: chez-shanpu
    ghq_root: '{{ lookup("env","HOME") }}/ghq'
    repos_root: '{{ ghq_root }}/github.com/{{ github_user }}'
    dotfiles_path: '{{ repos_root }}/dotfiles'
  roles:
    - name: common
      tags: common

    - name: font
      tags: font

    - name: dotfiles
      tags: dotfiles

    - name: fish
      tags: fish

    - name: language
      tags: language

    - name: docker
      tags: docker

    - name: editor
      tags: editor

    - name: terminal
      tags: terminal

    - name: gitkraken
      tags: gitkraken

    - name: kubernetes
      tags: kubernetes

#    - name: tex
#      tags: tex