---
- name: Install packages
  become: yes
  apt:
    name: '{{ env_dependences }}'
    update_cache: yes
    autoclean: yes
    autoremove: yes

- block:
    - name: install "anyenv"
      git:
        repo: https://github.com/riywo/anyenv
        dest: ~/.anyenv

    - name: init anyenv
      shell: anyenv install --init
      args:
        stdin: "y"
      ignore_errors: yes
      changed_when: false

    - name: reload fish
      shell: source ~/.config/fish/config.fish
      changed_when: false

  tags: anyenv_isntall

- block:
    - name: install "anyenv-update"
      git:
        repo: https://github.com/znz/anyenv-update.git
        dest: ~/.anyenv/plugins/anyenv-update

  tags: anyenv_plugin_install
