---
- name: install dep
  shell: go get -u github.com/golang/dep/cmd/dep
  changed_when: false
  tags: dep_install

- name: install ghq
  shell: go get github.com/motemen/ghq
  changed_when: false
  tags: ghq_install

- block:
    - name: git clone peco
      git:
        repo: https://github.com/peco/peco
        dest: '~/go/{{ go_versions }}/src/github.com/peco/peco'
        force: yes
      changed_when: false

    - name: build peco
      make:
        chdir: '~/go/{{ go_versions }}/src/github.com/peco/peco'
      changed_when: false

    - name: copy peco-bin to go-bin-dir
      copy:
        src: '~/go/{{ go_versions }}/src/github.com/peco/peco/releases/peco_linux_amd64/peco'
        dest: '~/go/{{ go_versions }}/bin/peco'
        mode: 0775
        force: yes
      changed_when: false

  tags: peco_install