---
- name: Install pyenv
  ansible.builtin.shell: anyenv install pyenv
  args:
    creates: ~/.anyenv/envs/pyenv/bin/pyenv
  changed_when: false

- name: reload fish
  ansible.builtin.shell: source ~/.config/fish/config.fish
  changed_when: false
