---
- block:
    - name: Install "ricty font"
      apt:
        name: fonts-ricty-diminished
        autoclean: yes
        autoremove: yes

    - name: Install "powerline font"
      apt:
        name: fonts-powerline
        autoclean: yes
        autoremove: yes

  tags: font_install