---
- block:
    - name: git clone kubectx kubens
      become: yes
      git:
        repo: https://github.com/ahmetb/kubectx
        dest: /opt/kubectx
        force: yes
      changed_when: false

    - name: Put kubectx to bin
      become: yes
      file:
        src: /opt/kubectx/kubectx
        dest: /usr/local/bin/kubectx
        state: link
        force: yes
      changed_when: false

    - name: Put kubens to bin
      become: yes
      file:
        src: /opt/kubectx/kubens
        dest: /usr/local/bin/kubens
        state: link
        force: yes
      changed_when: false

    - name: Put kubectx.fish to fish-config
      file:
        src: /opt/kubectx/completion/kubectx.fish
        dest: ~/.config/fish/completions/kubectx.fish
        state: link
        force: yes
      changed_when: false

    - name: Put kubens.fish to fish-config
      file:
        src: /opt/kubectx/completion/kubens.fish
        dest: ~/.config/fish/completions/kubens.fish
        state: link
        force: yes
      changed_when: false

  tags: kubectx_install