---
- name: Install packages
  become: yes
  apt:
    name:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install "anyenv"
  git:
    repo: https://github.com/riywo/anyenv
    dest: ~/.anyenv

- name: init anyenv
  shell: anyenv install --init
  args:
    stdin: "y"
  ignore_errors: yes
  changed_when: false

- name: reload fish
  shell: source ~/.config/fish/config.fish
  changed_when: false

- name: install "anyenv-update"
  git:
    repo: https://github.com/znz/anyenv-update.git
    dest: ~/.anyenv/plugins/anyenv-update
