---
- name: Install anyenv
  community.general.homebrew:
    name: anyenv

- name: init anyenv
  shell: anyenv install --init
  args:
    stdin: "y"
  ignore_errors: yes
  changed_when: false

#- name: reload fish
#  shell: source ~/.config/fish/config.fish
#  changed_when: false

- name: install "anyenv-update"
  git:
    repo: https://github.com/znz/anyenv-update.git
    dest: ~/.anyenv/plugins/anyenv-update
