---
- name: Install anyenv
  community.general.homebrew:
    name: anyenv

- name: init anyenv
  ansible.builtin.shell: anyenv install --init
  args:
    stdin: "y"
  ignore_errors: true
  changed_when: false

- name: install "anyenv-update"
  ansible.builtin.git:
    repo: https://github.com/znz/anyenv-update.git
    dest: ~/.anyenv/plugins/anyenv-update
