---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - git
      - libssl-dev
      - llvm
      - make
      - python3
      - python3-pip
      - python-is-python3
      - trash-cli
      - wget
    autoclean: true
    autoremove: true
    update_cache: true

- name: Upgrade all packages to the latest version
  become: true
  ansible.builtin.apt:
    upgrade: safe
  changed_when: false

- name: Update homebrew
  changed_when: false
  community.general.homebrew:
    update_homebrew: true

- name: Install tools by brew
  community.general.homebrew:
    name:
      - asdf
      - bat
      - direnv
      - eza
      - fd
      - gh
      - ghq
      - peco
      - uv
      - ripgrep

- name: Install tools by brew --build-from-source
  community.general.homebrew:
    name:
      - duf
    install_options: build-from-source
