---
- name: Install tmux
  community.general.homebrew:
    name: tmux

- name: Install Python tools with uv
  ansible.builtin.shell: |
    uv tool install {{ item }}
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
    executable: /bin/bash
  with_items:
    - powerline-status
    - powerline-mem-segment
    - psutil
