---
- name: Install tmux
  community.general.homebrew:
    name: tmux

- name: Install tmux powerline pip dependencies
  ansible.builtin.pip:
    name:
      - powerline-status
      - powerline-mem-segment
      - psutil
    executable: pip3
