---
- name: Install tmux
  community.general.homebrew:
    name: tmux

- name: Install powerline-status with uv
  ansible.builtin.shell: |
    uv tool install powerline-status --with psutil
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/powerline"
    executable: /bin/bash
