---
- block:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: safe

    - name: Install packages
      apt:
        name: '{{ item }}'
      with_items:
        - '{{ apt_packages }}'

    - name: Apt clean
      apt:
        autoclean: yes

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

  tags: apt_install

- name: Display date in Gnome shell
  command: gsettings set org.gnome.desktop.interface clock-show-date true