---
- block:
    - name: Apt update
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      become: yes
      apt:
        upgrade: safe

    - name: Install packages
      become: yes
      apt:
        name: '{{ apt_packages }}'

    - name: Apt clean
      become: yes
      apt:
        autoclean: yes

    - name: Remove unnecessary packages
      become: yes
      apt:
        autoremove: yes

  tags: apt_install

# docker上で実行するとだめ？ TODO 要検証
#- block:
#    - name: Install pip "psutil" for dconf
#      pip:
#        name: psutil
#
#    - name: Display date in Gnome shell
#      dconf:
#        key: "/org/gnome/desktop/interface/clock-show-date"
#        value: "true"
#        state: present
#
#  tags: edit_gnome_shell