---
- name: Install dependencies
  become: yes
  apt:
    name: '{{ docker_dependences }}'
    update_cache: yes

- name: Obtain ubuntu codename
  shell: lsb_release -cs
  register: ubuntu_codename
  check_mode: no
  failed_when: False
  changed_when: False

- name: Add GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    state: present
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    name: '{{ docker_apt_packages }}'
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Add user to docker group
  become: yes
  user:
    name: '{{ ansible_user }}'
    append: yes
    groups:
      - docker