---
- name: Create Downloads dir if it doesn`t exist
  file:
    path: ~/Downloads
    state: directory

- name: Get deb Hyper-term
  get_url:
    url: https://releases.hyper.is/download/deb
    dest: '{{ ansible_env.HOME }}/Downloads/hyper-term.deb'
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5
  changed_when: false

- name: Install Hyper-term
  become: yes
  apt:
    deb: '{{ ansible_env.HOME }}/Downloads/hyper-term.deb'
