---
- name: Install neovim nighty
  community.general.homebrew:
    state: head
    name:
    - 'luajit'
    - 'neovim'

- name: Install neovim dependencies
  community.general.homebrew:
    name:
    - 'node'

- name: Download install script for dein.vim
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: ~/.config/nvim/installer.sh
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5

- name: Install dein.vim
  shell: sh ~/.config/nvim/installer.sh ~/.cache/dein
  args:
    creates: ~/.cache/dein/repos/github.com/Shougo/dein.vim
  changed_when: false
