---
- name: Unlink existing luajit if present
  ansible.builtin.shell: |
    if brew list luajit &>/dev/null; then
      brew unlink luajit || true
    fi
  args:
    executable: /bin/bash
  changed_when: false

- name: Install luajit head version
  community.general.homebrew:
    state: head
    name:
      - 'luajit'

- name: Install neovim nighty
  community.general.homebrew:
    state: head
    name:
      - 'neovim'

- name: Install neovim dependencies
  community.general.homebrew:
    name:
      - 'node'

# todo install pynvim

- name: Create nvim config dir
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: Create dein cache directory
  ansible.builtin.file:
    path: ~/.cache/dein
    state: directory

- name: Download dein-installer script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Shougo/dein-installer.vim/master/installer.sh
    dest: /tmp/dein-installer.sh
    mode: '0755'

- name: Install dein.vim using dein-installer
  ansible.builtin.shell: sh /tmp/dein-installer.sh --use-neovim-config --overwrite-config ~/.cache/dein
  args:
    creates: ~/.cache/dein/repos/github.com/Shougo/dein.vim
  changed_when: false
