---
- name: Install neovim and its dependencies
  become: true
  ansible.builtin.apt:
    name:
    - neovim
    - luajit
    - python3-neovim
    autoclean: true
    autoremove: true
    update_cache: true

- name: Install node
  become: true
  ansible.builtin.apt:
    name: nodejs
    autoclean: true
    autoremove: true
    update_cache: true
