---
- name: Setup nvim in Darwin
  ansible.builtin.include_tasks: darwin.yaml
  when: ansible_os_family == "Darwin"

- name: Setup nvim in Debian
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family == "Debian"
